---
title: "Commits Analisis de regresion"
author: "Ronald Bailey"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Configuracion de Git para que los comandos magicos funcionen


```{r}
system("git config --global user.email \"ronald.bailey@galileo.edu\"")
system("git config --global user.name \"ronaldbailey\"")

```




## Commit 1

```{r}

system("git add .")
system("git commit -m \"Primer commit\"")
system("git push")
```


## Commit 2

```{r}

system("git add .")
system("git commit -m \"Leer datos\"")
system("git push")
```

## Commit 3

```{r}

system("git add .")
system("git commit -m \"Texto del ejercicio 1\"")
system("git push")
```
```{r}

system("git add .")
system("git commit -m \"Ejercicio 1 completo nombres\"")
system("git push")
```




```{r}

system("git add .")
system("git commit -m \"Ejercicio 1 Readme\"")
system("git push")
```
```{r}

system("git add .")
system("git commit -m \"Ejercicio 2\"")
system("git push")
```




```{r}

system("git add .")
system("git commit -m \"Ejercicio 2 tema 4\"")
system("git push")
```
```{r}

system("git add .")
system("git commit -m \"Ejercicio 2 tema 4 \"")
system("git push")
```
```{r}

system("git add .")
system("git commit -m \"Ejercicio 2 tema 6 \"")
system("git push")
```

```{r}

system("git add .")
system("git commit -m \"Ejercicio 2 tema 6 final\"")
system("git push")
```

```{r}

system("git add .")
system("git commit -m \"Ejercicio 2 tema 4 \"")
system("git push")
```
```{r}

system("git add .")
system("git commit -m \"Ejercicio 2 tema 6 \"")
system("git push")
```

```{r}

system("git add .")
system("git commit -m \"Ejercicio 3 tema 2 \"")
system("git push")
```



```{r}

system("git add .")
system("git commit -m \"Ejercicio 3 tema 2 2 \"")
system("git push")
```